# Generated by Django 5.0.6 on 2024-06-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=50)),
                ('priceNormal', models.CharField(max_length=50)),
                ('priceCard', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialtie', models.CharField(max_length=50)),
                ('priceNormal', models.CharField(max_length=50)),
                ('priceCard', models.CharField(max_length=50)),
            ],
        ),
    ]
